---
title: "testing_function"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(stringr)
library(tidyverse)
library(foreach)
library(expss)
devtools::load_all()
library(parallel)
# cl <- makeCluster(parallel::detectCores() / 2)
# doParallel::registerDoParallel(cl)

library(foreach)
future::plan("multisession", workers = 4)

```


```{r}

pop_dat <- readRDS("/Users/dinan_elsyad/Desktop/summer research/sim-studies/sandbox/sim_samp.rds")
#pop_dat <- readRDS("/home/grayson/Documents/UFDS2023/sim-studies/sandbox/sim_samp.rds")

counties <- unique(pop_dat$DOMAIN)

samp_dat <- data.frame(matrix(ncol = ncol(pop_dat), nrow = 0))
colnames(samp_dat) <- colnames(pop_dat)

#creating sample data 
for (i in 1:length(counties)) {
  sub <- subset(pop_dat, DOMAIN == counties[i])
  num_plot <- as.integer(.15 * nrow(sub))
  
  samp_plots <- sub %>%
        slice_sample(n = num_plot, replace = FALSE) %>%
        as.data.frame()
  
  samp_dat <- rbind(samp_dat, samp_plots)
}

#removing response variable from county data 
pop_dat <-  pop_dat[,-c(28:33)]


```


## test

```{r}

#correct_one <- zi_est

##do future 
devtools::load_all()
set.seed(10)
t1 <- Sys.time()
zi_est <- unit_zi(samp_dat, pop_dat, DRYBIO ~ tcc, domain_level = "SUBSECTION", mse_est = T, B = 1500)
t2 <- Sys.time()
t2 - t1 
#foeach, dopar: 8.17908, 8.027853
### all B = 1500
#foeach, dofuture, B = 1500: 54.21819 
#furrr, loaded future cores 56.38872, 59.54396, 53.96114
#furrrr, loaded regular core stuff : 55.30214, 56.5665
#furrr, loaded regular core plus progress bar: 1.007585, 57.53013
#furrr, future cores plus progres bar: 56.21319, 54.7398

```


