# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_cpp <- function(beta_lm, beta_glm, names, dom_input, u, design_mat_lm, design_mat_glm) {
    .Call(`_saeczi_predict_cpp`, beta_lm, beta_glm, names, dom_input, u, design_mat_lm, design_mat_glm)
}

