# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_zi <- function(beta_lm, beta_glm, u_lm, u_glm, design_mat_lm, design_mat_glm) {
    .Call(`_saeczi_predict_zi`, beta_lm, beta_glm, u_lm, u_glm, design_mat_lm, design_mat_glm)
}

match_val <- function(names, values, input) {
    .Call(`_saeczi_match_val`, names, values, input)
}

